STACK1	SEGMENT PARA STACK
STACK_AREA	DB 100H DUP(?)
STACK1	ENDS

DATA	SEGMENT	PARA 
VALUE	DW	0011101000101111B ;3A2F
DATA 	ENDS

CODE	SEGMENT	PARA
        ASSUME  CS:CODE,SS:STACK1,DS:DATA
MAIN	PROC 	FAR
		MOV		AX,DATA
		MOV		DS,AX
		MOV		BX,VALUE
		MOV		CX,4 ;循环次数
SHIFT:	PUSH	CX
		MOV		CL,4
		ROL		BX,CL ;BX循环左移4位
		MOV		AL,BL ;取出低8位
		AND		AL,0FH;清除高四位，只留最低四位
		ADD		AL,30H
		CMP		AL,39H
		JBE		PRINT
		ADD		AL,'A'-'9'-1
PRINT:	MOV		DL,AL
		MOV		AH,2
		INT 	21H
		POP		CX
		LOOP	SHIFT
EXIT:	MOV		AX,4C00H
		INT		21H
MAIN	ENDP
CODE	ENDS
		END 	MAIN